spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=pmgmt_db
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
